/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const VlogCategory = IDL.Variant({
  'vlog' : IDL.Null,
  'trading' : IDL.Null,
  'promo' : IDL.Null,
});
export const Ad = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'linkUrl' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
});
export const AdminDashboardStats = IDL.Record({
  'totalPendingWithdrawals' : IDL.Nat,
  'totalPlatformBalance' : IDL.Nat,
  'totalPendingDeposits' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalPendingEarnRecords' : IDL.Nat,
});
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DepositRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'username' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'reviewedAt' : IDL.Int,
  'currency' : IDL.Text,
  'txHash' : IDL.Text,
  'amount' : IDL.Text,
});
export const EarnRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'contentId' : IDL.Text,
  'username' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'taskType' : IDL.Variant({
    'writeArticle' : IDL.Null,
    'watchVideo' : IDL.Null,
  }),
  'amount' : IDL.Nat,
});
export const WithdrawalRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'username' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'walletAddress' : IDL.Text,
  'reviewedAt' : IDL.Int,
  'currency' : IDL.Text,
  'amount' : IDL.Nat,
});
export const UserAccount = IDL.Record({
  'username' : IDL.Text,
  'balance' : IDL.Nat,
  'totalEarned' : IDL.Nat,
  'passwordHash' : IDL.Vec(IDL.Nat8),
  'totalDeposited' : IDL.Nat,
});
export const VlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'category' : VlogCategory,
  'videoUrl' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveDeposit' : IDL.Func([IDL.Nat], [], []),
  'approveEarnRecord' : IDL.Func([IDL.Nat], [], []),
  'approveWithdrawal' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimEarnForArticle' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'claimEarnForVideo' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'createAd' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'createAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createVlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, VlogCategory],
      [],
      [],
    ),
  'deleteAd' : IDL.Func([IDL.Nat], [], []),
  'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
  'deleteVlogPost' : IDL.Func([IDL.Nat], [], []),
  'fetchCryptoPrices' : IDL.Func([], [IDL.Text], []),
  'fetchWorldNews' : IDL.Func([], [IDL.Text], []),
  'getActiveAds' : IDL.Func([], [IDL.Vec(Ad)], ['query']),
  'getAdminStats' : IDL.Func([], [AdminDashboardStats], ['query']),
  'getAnnouncement' : IDL.Func([IDL.Nat], [Announcement], ['query']),
  'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPendingDeposits' : IDL.Func([], [IDL.Vec(DepositRequest)], ['query']),
  'getPendingEarnRecords' : IDL.Func([], [IDL.Vec(EarnRecord)], ['query']),
  'getPendingWithdrawals' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getUserAccount' : IDL.Func([], [IDL.Opt(UserAccount)], ['query']),
  'getUserDeposits' : IDL.Func([], [IDL.Vec(DepositRequest)], ['query']),
  'getUserEarnRecords' : IDL.Func([], [IDL.Vec(EarnRecord)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserWithdrawals' : IDL.Func([], [IDL.Vec(WithdrawalRequest)], ['query']),
  'getVlogPost' : IDL.Func([IDL.Nat], [VlogPost], ['query']),
  'getVlogPosts' : IDL.Func([], [IDL.Vec(VlogPost)], ['query']),
  'getVlogPostsByCategory' : IDL.Func(
      [VlogCategory],
      [IDL.Vec(VlogPost)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [], []),
  'rejectDeposit' : IDL.Func([IDL.Nat], [], []),
  'rejectEarnRecord' : IDL.Func([IDL.Nat], [], []),
  'rejectWithdrawal' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitDepositRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitWithdrawalRequest' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAd' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'updateAnnouncement' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateVlogPost' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, VlogCategory],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const VlogCategory = IDL.Variant({
    'vlog' : IDL.Null,
    'trading' : IDL.Null,
    'promo' : IDL.Null,
  });
  const Ad = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'linkUrl' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
  });
  const AdminDashboardStats = IDL.Record({
    'totalPendingWithdrawals' : IDL.Nat,
    'totalPlatformBalance' : IDL.Nat,
    'totalPendingDeposits' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalPendingEarnRecords' : IDL.Nat,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DepositRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'username' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'reviewedAt' : IDL.Int,
    'currency' : IDL.Text,
    'txHash' : IDL.Text,
    'amount' : IDL.Text,
  });
  const EarnRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'contentId' : IDL.Text,
    'username' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'taskType' : IDL.Variant({
      'writeArticle' : IDL.Null,
      'watchVideo' : IDL.Null,
    }),
    'amount' : IDL.Nat,
  });
  const WithdrawalRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'username' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'walletAddress' : IDL.Text,
    'reviewedAt' : IDL.Int,
    'currency' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const UserAccount = IDL.Record({
    'username' : IDL.Text,
    'balance' : IDL.Nat,
    'totalEarned' : IDL.Nat,
    'passwordHash' : IDL.Vec(IDL.Nat8),
    'totalDeposited' : IDL.Nat,
  });
  const VlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'category' : VlogCategory,
    'videoUrl' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveDeposit' : IDL.Func([IDL.Nat], [], []),
    'approveEarnRecord' : IDL.Func([IDL.Nat], [], []),
    'approveWithdrawal' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimEarnForArticle' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'claimEarnForVideo' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'createAd' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'createAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createVlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, VlogCategory],
        [],
        [],
      ),
    'deleteAd' : IDL.Func([IDL.Nat], [], []),
    'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
    'deleteVlogPost' : IDL.Func([IDL.Nat], [], []),
    'fetchCryptoPrices' : IDL.Func([], [IDL.Text], []),
    'fetchWorldNews' : IDL.Func([], [IDL.Text], []),
    'getActiveAds' : IDL.Func([], [IDL.Vec(Ad)], ['query']),
    'getAdminStats' : IDL.Func([], [AdminDashboardStats], ['query']),
    'getAnnouncement' : IDL.Func([IDL.Nat], [Announcement], ['query']),
    'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPendingDeposits' : IDL.Func([], [IDL.Vec(DepositRequest)], ['query']),
    'getPendingEarnRecords' : IDL.Func([], [IDL.Vec(EarnRecord)], ['query']),
    'getPendingWithdrawals' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getUserAccount' : IDL.Func([], [IDL.Opt(UserAccount)], ['query']),
    'getUserDeposits' : IDL.Func([], [IDL.Vec(DepositRequest)], ['query']),
    'getUserEarnRecords' : IDL.Func([], [IDL.Vec(EarnRecord)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserWithdrawals' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getVlogPost' : IDL.Func([IDL.Nat], [VlogPost], ['query']),
    'getVlogPosts' : IDL.Func([], [IDL.Vec(VlogPost)], ['query']),
    'getVlogPostsByCategory' : IDL.Func(
        [VlogCategory],
        [IDL.Vec(VlogPost)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [], []),
    'rejectDeposit' : IDL.Func([IDL.Nat], [], []),
    'rejectEarnRecord' : IDL.Func([IDL.Nat], [], []),
    'rejectWithdrawal' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitDepositRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitWithdrawalRequest' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAd' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'updateAnnouncement' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateVlogPost' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, VlogCategory],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };