/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Ad {
  'id' : bigint,
  'title' : string,
  'linkUrl' : string,
  'createdAt' : bigint,
  'description' : string,
  'isActive' : boolean,
  'imageUrl' : string,
}
export interface AdminDashboardStats {
  'totalPendingWithdrawals' : bigint,
  'totalPlatformBalance' : bigint,
  'totalPendingDeposits' : bigint,
  'totalUsers' : bigint,
  'totalPendingEarnRecords' : bigint,
}
export interface Announcement {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
}
export interface DepositRequest {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'username' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'reviewedAt' : bigint,
  'currency' : string,
  'txHash' : string,
  'amount' : string,
}
export interface EarnRecord {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'contentId' : string,
  'username' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'taskType' : { 'writeArticle' : null } |
    { 'watchVideo' : null },
  'amount' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserAccount {
  'username' : string,
  'balance' : bigint,
  'totalEarned' : bigint,
  'passwordHash' : Uint8Array,
  'totalDeposited' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VlogCategory = { 'vlog' : null } |
  { 'trading' : null } |
  { 'promo' : null };
export interface VlogPost {
  'id' : bigint,
  'title' : string,
  'thumbnailUrl' : string,
  'createdAt' : bigint,
  'description' : string,
  'category' : VlogCategory,
  'videoUrl' : string,
}
export interface WithdrawalRequest {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'username' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'walletAddress' : string,
  'reviewedAt' : bigint,
  'currency' : string,
  'amount' : bigint,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveDeposit' : ActorMethod<[bigint], undefined>,
  'approveEarnRecord' : ActorMethod<[bigint], undefined>,
  'approveWithdrawal' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimEarnForArticle' : ActorMethod<[string, string], undefined>,
  'claimEarnForVideo' : ActorMethod<[string, bigint], undefined>,
  'createAd' : ActorMethod<[string, string, string, string], undefined>,
  'createAnnouncement' : ActorMethod<[string, string], undefined>,
  'createVlogPost' : ActorMethod<
    [string, string, string, string, VlogCategory],
    undefined
  >,
  'deleteAd' : ActorMethod<[bigint], undefined>,
  'deleteAnnouncement' : ActorMethod<[bigint], undefined>,
  'deleteVlogPost' : ActorMethod<[bigint], undefined>,
  'fetchCryptoPrices' : ActorMethod<[], string>,
  'fetchWorldNews' : ActorMethod<[], string>,
  'getActiveAds' : ActorMethod<[], Array<Ad>>,
  'getAdminStats' : ActorMethod<[], AdminDashboardStats>,
  'getAnnouncement' : ActorMethod<[bigint], Announcement>,
  'getAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPendingDeposits' : ActorMethod<[], Array<DepositRequest>>,
  'getPendingEarnRecords' : ActorMethod<[], Array<EarnRecord>>,
  'getPendingWithdrawals' : ActorMethod<[], Array<WithdrawalRequest>>,
  'getUserAccount' : ActorMethod<[], [] | [UserAccount]>,
  'getUserDeposits' : ActorMethod<[], Array<DepositRequest>>,
  'getUserEarnRecords' : ActorMethod<[], Array<EarnRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserWithdrawals' : ActorMethod<[], Array<WithdrawalRequest>>,
  'getVlogPost' : ActorMethod<[bigint], VlogPost>,
  'getVlogPosts' : ActorMethod<[], Array<VlogPost>>,
  'getVlogPostsByCategory' : ActorMethod<[VlogCategory], Array<VlogPost>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[string, Uint8Array], undefined>,
  'rejectDeposit' : ActorMethod<[bigint], undefined>,
  'rejectEarnRecord' : ActorMethod<[bigint], undefined>,
  'rejectWithdrawal' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitDepositRequest' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'submitWithdrawalRequest' : ActorMethod<
    [string, bigint, string, string],
    undefined
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAd' : ActorMethod<
    [bigint, string, string, string, string, boolean],
    undefined
  >,
  'updateAnnouncement' : ActorMethod<[bigint, string, string], undefined>,
  'updateVlogPost' : ActorMethod<
    [bigint, string, string, string, string, VlogCategory],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];